server:
    port: 8110
    servlet:
        context-path: /api/v1/

services:
    olive-insurance-administration-service:
        base-url: ${ADMINISTRATION_SERVICE_URL}

olive:
    company:
        amsa: "1fd4143f-1a73-4b43-963a-b1dbc10cb4bb"
    marketLevel:
        pool-tpv: "62e72106-cfb6-4dc0-9e09-a9fad2aa68b2"

spring:
    application:
        name: dev-olive-insurance-auth-service
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                use_sql_comments: true
        generate-ddl: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect

    # Configuration spécifique au développement
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true

    # Logs plus détaillés en développement
    logging:
        level:
            org.hibernate.SQL: DEBUG
            org.hibernate.type.descriptor.sql.BasicBinder: TRACE
            org.springframework.security: DEBUG
    cloud:
        consul:
            host: ${SPRING_CLOUD_CONSUL_HOST}
            port: ${SPRING_CLOUD_CONSUL_PORT}
            discovery:
                register: ${SPRING_CLOUD_CONSUL_DISCOVERY_REGISTER:true}
                deregister: ${SPRING_CLOUD_CONSUL_DISCOVERY_DEREGISTER:true}
                health-check-path: ${SPRING_CLOUD_CONSUL_DISCOVERY_HEALTHCHECKPATH:/api/v1/actuator/health}
                prefer-ip-address: ${SPRING_CLOUD_CONSUL_DISCOVERY_PREFER_IP_ADDRESS:true}
    mail:
        host: ${SPRING_MAIL_HOST:localhost}
        port: ${SPRING_MAIL_PORT:1025}
        username: ""
        password: ""
        properties:
            mail:
                smtp:
                    auth: false
                    starttls:
                        enable: false

management:
    endpoints:
        web:
            exposure:
                include: health,info

jwt:

    service:
        issuer: olive-insurance
        private-key: classpath:keys/services/private-jwt.pem
        public-key: classpath:keys/services/public-jwt.pem
        expiration: 3600000 # 1 hour

    user:
        private-key: classpath:keys/jwt/private-user.pem
        public-key: classpath:keys/jwt/public-user.pem
        expiration: 36000000 # 10 min

    admin:
        private-key: classpath:keys/jwt/private-admin.pem
        public-key: classpath:keys/jwt/public-admin.pem
        expiration: 3600000 # 5 min

    refresh:
        expiration: 604800000 # 7 days

trusted-services:
    auth-service: classpath:keys/services/auth-public.pem
    administration-service: classpath:keys/services/administration-public.pem
